AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Function Triggered by Kinesis Stream

Resources:
  TransactionsInputStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: TransactionsInputStream
      ShardCount: 1

  TransactionsOutputStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: TransactionsOutputStream
      ShardCount: 1

  FlinkApplicationRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "kinesisanalytics.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "FlinkApplicationPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: "ReadCode"
                Effect: "Allow"
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                Resource: "arn:aws:s3:::flink-transactions-code-259984666282/flink-fraud-detection-1.0.jar"
              - Sid: "ListCloudwatchLogGroups"
                Effect: "Allow"
                Action: "logs:DescribeLogGroups"
                Resource: "arn:aws:logs:us-east-1:259984666282:log-group:*"
              - Sid: "ListCloudwatchLogStreams"
                Effect: "Allow"
                Action: "logs:DescribeLogStreams"
                Resource: "arn:aws:logs:us-east-1:259984666282:log-group:/aws/kinesis-analytics/FlinkAppManual:log-stream:*"
              - Sid: "PutCloudwatchLogs"
                Effect: "Allow"
                Action: "logs:PutLogEvents"
                Resource: "arn:aws:logs:us-east-1:259984666282:log-group:/aws/kinesis-analytics/FlinkAppManual:log-stream:kinesis-analytics-log-stream"
              - Sid: "ReadInputStream"
                Effect: "Allow"
                Action: "kinesis:*"
                Resource: "arn:aws:kinesis:us-east-1:259984666282:stream/TransactionsInputStream"
              - Sid: "WriteOutputStream"
                Effect: "Allow"
                Action: "kinesis:*"
                Resource: "arn:aws:kinesis:us-east-1:259984666282:stream/TransactionsOutputStream"

  FlinkApplication:
    Type: "AWS::KinesisAnalyticsV2::Application"
    Properties:
      ApplicationName: "FlinkTransactionProcessing"
      RuntimeEnvironment: "FLINK-1_15"
      ServiceExecutionRole: !GetAtt FlinkApplicationRole.Arn
      ApplicationConfiguration:
        ApplicationCodeConfiguration:
          CodeContent:
            S3ContentLocation:
              BucketARN: !Sub "arn:aws:s3:::flink-transactions-code-259984666282"
              FileKey: "flink-fraud-detection-1.0.jar"
          CodeContentType: "ZIPFILE"
        EnvironmentProperties:
          PropertyGroups:
            - PropertyGroupId: "ProducerConfigProperties"
              PropertyMap:
                "flink.inputstream.initpos": "LATEST"
                "aws.region": "us-east-1"
                "AggregationEnabled": "false"
            - PropertyGroupId: "ConsumerConfigProperties"
              PropertyMap:
                "aws.region": "us-east-1"
